sqlhost: 120.48.17.34:27621 # sql数据库主机IP地址
sqluser: root # sql数据库用户名
sqlpwd: stvsl2060 # sql数据库密码
sqldbname: SSIMP # sql数据库名称
sqlMaxIdleConns: 10 # 最大数据库空闲连接数
sqlMaxOpenConns: 30 # 最大数据库连接数
sqlConnMaxLifetime: 2 # 单个数据库连接最大生命周期
redishost: 120.48.17.34:5210 # redis主机地址以及端口
redispwd: stvsl2060 # redis密码
redisPoolSize: 30 # redis连接池大小
rsaUpdateLifecycle: 120 # rsa更新周期，单位分钟
logFormat: text # 日志格式
logDir: ./log # 日志目录
