sqlhost:  # sql数据库主机IP地址
sqluser:  # sql数据库用户名
sqlpwd:  # sql数据库密码
sqldbname:  # sql数据库名称
sqlMaxIdleConns:  # 最大数据库空闲连接数
sqlMaxOpenConns:  # 最大数据库连接数
sqlConnMaxLifetime:  # 单个数据库连接最大生命周期
redishost:  # redis主机地址以及端口
redispwd:  # redis密码
redisPoolSize:  # redis连接池大小
rsaUpdateLifecycle:  # rsa更新周期，单位分钟
logFormat:  # 日志格式
logDir:  # 日志目录
logKeepDays:  # 日志保留天数
cosBucket:  # cos桶名称
cosRegion:  # cos地域
cosAppid:   # cos appid
cosSecretId:  # cosSecretId
cosSecretKey:   # cosSecretKey
cosDomain: # cos域名